apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-deploy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_USER/auto-deploy-project'
    path: 'k8s'
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: auto-deploy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
